Update build system
Put common code into a file Makefile.gappkg shared by multiple packages, which
has various bugfixes and improvements applied; in the future, this will make
it easier to share further improvements between packages.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,20 @@
 #!/bin/sh
 # usage: configure gappath
 # this script creates a `Makefile' from `Makefile.in'
-if test -z "$1"; then
-  GAPPATH=../..; echo "Using ../.. as default GAP path";
-else
-  GAPPATH=$1;
-fi
 
-if test ! -r $GAPPATH/sysinfo.gap ; then
+set -e
+
+GAPPATH=../..
+while test "$#" -ge 1 ; do
+  option="$1" ; shift
+  case "$option" in
+    --with-gaproot=*) GAPPATH=${option#--with-gaproot=}; ;;
+    -*)               echo "ERROR: unsupported argument $option" ; exit 1;;
+    *)                GAPPATH="$option" ;;
+  esac
+done
+
+if test ! -r "$GAPPATH/sysinfo.gap" ; then
     echo
     echo "No file $GAPPATH/sysinfo.gap found."
     echo
@@ -18,15 +25,10 @@ if test ! -r $GAPPATH/sysinfo.gap ; then
     echo "Either your GAPPATH is incorrect or the GAP it is pointing to"
     echo "is not properly compiled (do \"./configure && make\" there first)."
     echo
-    echo Aborting... No Makefile is generated.
+    echo "Aborting... No Makefile is generated."
     echo
     exit 1
 fi
 
-echo "Using config in $GAPPATH/sysinfo.gap"
-
-. "$GAPPATH/sysinfo.gap"
-sed \
-    -e "s;@GAPARCH@;$GAParch;g" \
-    -e "s;@GAPPATH@;$GAPPATH;g" \
-    Makefile.in > Makefile
+echo "Using settings from $GAPPATH/sysinfo.gap"
+sed -e "s;@GAPPATH@;$GAPPATH;g" Makefile.in > Makefile
